<?php
namespace tests\Unit\Classes\Parsers;

use App\Classes\DateFormatter\ConvertToLaravelFormat;
use App\Classes\LogParsers\UserFileParser;
use App\Classes\Observers\Log\LogParserObserver;
use Tests\TestCase;

/**
 * @covers \App\Classes\Parsers\UserFileParser
 */
class UserFileParserTest extends TestCase
{
    private $parser;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->parser = new UserFileParser;
    }

    /**
     * Test parsing a log file
     */
    public function testParse()
    {
        $logFilePath = '/var/www/html/logs.txt';
        $result = $this->parser->parse($logFilePath);
        $this->assertEquals('Parsing log file is complete', $result);
    }

    /**
     * Test parsing a non-existent log file
     */
    public function testParseNonExistentFile()
    {
        $logFilePath = __DIR__ . '/non-existent.log';
        $result = $this->parser->parse($logFilePath);

        $this->assertEquals('Log file is not exist.', $result);
    }

    public function testParseNonReadableFile()
    {
        //
    }
}